minimumReleaseAge: 0

minimumReleaseAgeExclude:
  - '@net-advantage/nabs-ui-accordion@0.36.0'
  - '@net-advantage/nabs-ui-avatar@0.36.0'
  - '@net-advantage/nabs-ui-buttons@0.36.0'
  - '@net-advantage/nabs-ui-cards@0.36.0'
  - '@net-advantage/nabs-ui-checkbox@0.36.0'
  - '@net-advantage/nabs-ui-code@0.36.0'
  - '@net-advantage/nabs-ui-combobox@0.36.0'
  - '@net-advantage/nabs-ui-datepicker@0.36.0'
  - '@net-advantage/nabs-ui-dialog@0.36.0'
  - '@net-advantage/nabs-ui-dropdownlist@0.36.0'
  - '@net-advantage/nabs-ui-dropdownmenu@0.36.0'
  - '@net-advantage/nabs-ui-dynamicform@0.36.0'
  - '@net-advantage/nabs-ui-fileupload@0.36.0'
  - '@net-advantage/nabs-ui-graph@0.36.0'
  - '@net-advantage/nabs-ui-grid@0.36.0'
  - '@net-advantage/nabs-ui-layout@0.36.0'
  - '@net-advantage/nabs-ui-markdown@0.36.0'
  - '@net-advantage/nabs-ui-navigation@0.36.0'
  - '@net-advantage/nabs-ui-panel@0.36.0'
  - '@net-advantage/nabs-ui-radiobutton@0.36.0'
  - '@net-advantage/nabs-ui-shell@0.36.0'
  - '@net-advantage/nabs-ui-signature@0.36.0'
  - '@net-advantage/nabs-ui-slider@0.36.0'
  - '@net-advantage/nabs-ui-stepper@0.36.0'
  - '@net-advantage/nabs-ui-tab@0.36.0'
  - '@net-advantage/nabs-ui-textarea@0.36.0'
  - '@net-advantage/nabs-ui-textbox@0.36.0'
  - '@net-advantage/nabs-ui-themes-dark@0.36.0'
  - '@net-advantage/nabs-ui-themes-light@0.36.0'
  - '@net-advantage/nabs-ui-themes@0.36.0'
  - '@net-advantage/nabs-ui-toolbar@0.36.0'
  - '@net-advantage/nabs-ui-accordion@0.37.0'
  - '@net-advantage/nabs-ui-avatar@0.37.0'
  - '@net-advantage/nabs-ui-buttons@0.37.0'
  - '@net-advantage/nabs-ui-cards@0.37.0'
  - '@net-advantage/nabs-ui-checkbox@0.37.0'
  - '@net-advantage/nabs-ui-code@0.37.0'
  - '@net-advantage/nabs-ui-combobox@0.37.0'
  - '@net-advantage/nabs-ui-datepicker@0.37.0'
  - '@net-advantage/nabs-ui-dialog@0.37.0'
  - '@net-advantage/nabs-ui-dropdownlist@0.37.0'
  - '@net-advantage/nabs-ui-dropdownmenu@0.37.0'
  - '@net-advantage/nabs-ui-dynamicform@0.37.0'
  - '@net-advantage/nabs-ui-fileupload@0.37.0'
  - '@net-advantage/nabs-ui-graph@0.37.0'
  - '@net-advantage/nabs-ui-grid@0.37.0'
  - '@net-advantage/nabs-ui-layout@0.37.0'
  - '@net-advantage/nabs-ui-markdown@0.37.0'
  - '@net-advantage/nabs-ui-navigation@0.37.0'
  - '@net-advantage/nabs-ui-panel@0.37.0'
  - '@net-advantage/nabs-ui-radiobutton@0.37.0'
  - '@net-advantage/nabs-ui-shell@0.37.0'
  - '@net-advantage/nabs-ui-signature@0.37.0'
  - '@net-advantage/nabs-ui-slider@0.37.0'
  - '@net-advantage/nabs-ui-stepper@0.37.0'
  - '@net-advantage/nabs-ui-tab@0.37.0'
  - '@net-advantage/nabs-ui-textarea@0.37.0'
  - '@net-advantage/nabs-ui-textbox@0.37.0'
  - '@net-advantage/nabs-ui-themes-dark@0.37.0'
  - '@net-advantage/nabs-ui-themes-light@0.37.0'
  - '@net-advantage/nabs-ui-themes@0.37.0'
  - '@net-advantage/nabs-ui-toolbar@0.37.0'
  - '@net-advantage/nabs-ui-accordion@0.38.0'
  - '@net-advantage/nabs-ui-avatar@0.38.0'
  - '@net-advantage/nabs-ui-buttons@0.38.0'
  - '@net-advantage/nabs-ui-cards@0.38.0'
  - '@net-advantage/nabs-ui-checkbox@0.38.0'
  - '@net-advantage/nabs-ui-code@0.38.0'
  - '@net-advantage/nabs-ui-combobox@0.38.0'
  - '@net-advantage/nabs-ui-datepicker@0.38.0'
  - '@net-advantage/nabs-ui-dialog@0.38.0'
  - '@net-advantage/nabs-ui-dropdownlist@0.38.0'
  - '@net-advantage/nabs-ui-dropdownmenu@0.38.0'
  - '@net-advantage/nabs-ui-dynamicform@0.38.0'
  - '@net-advantage/nabs-ui-fileupload@0.38.0'
  - '@net-advantage/nabs-ui-graph@0.38.0'
  - '@net-advantage/nabs-ui-grid@0.38.0'
  - '@net-advantage/nabs-ui-layout@0.38.0'
  - '@net-advantage/nabs-ui-markdown@0.38.0'
  - '@net-advantage/nabs-ui-navigation@0.38.0'
  - '@net-advantage/nabs-ui-panel@0.38.0'
  - '@net-advantage/nabs-ui-radiobutton@0.38.0'
  - '@net-advantage/nabs-ui-shell@0.38.0'
  - '@net-advantage/nabs-ui-signature@0.38.0'
  - '@net-advantage/nabs-ui-slider@0.38.0'
  - '@net-advantage/nabs-ui-stepper@0.38.0'
  - '@net-advantage/nabs-ui-tab@0.38.0'
  - '@net-advantage/nabs-ui-textarea@0.38.0'
  - '@net-advantage/nabs-ui-textbox@0.38.0'
  - '@net-advantage/nabs-ui-themes-dark@0.38.0'
  - '@net-advantage/nabs-ui-themes-light@0.38.0'
  - '@net-advantage/nabs-ui-themes@0.38.0'
  - '@net-advantage/nabs-ui-toolbar@0.38.0'
