<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>1f0b58a6-4d6f-4f29-b47c-949812642b13</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NabsPrefix.Api\NabsPrefix.Api.csproj" />
    <ProjectReference Include="..\NabsPrefix.Gateway\NabsPrefix.Gateway.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" />
  </ItemGroup>
</Project>
